---
platform: linux

image_resource:
  type: docker-image
  source: {repository: docker, tag: dind}

inputs:
- name: core-busyboxplus
- name: buildroot

outputs:
- name: image-root

params:
  FLAVOR:

run:
  path: core-busyboxplus/ci/build
