---
platform: linux

image_resource:
  type: docker-image
  source: {repository: docker, tag: dind}

inputs:
- name: buildroot-images
- name: buildroot
- name: buildroot-tarmaker-image

outputs:
- name: image-root

params:
  FLAVOR:

run:
  path: buildroot-images/ci/build
